# Generated by Django 4.1.7 on 2024-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='elec_mpan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='elec_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='gas_mprn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='gas_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
